arrowParens: always
jsxSingleQuote: true
proseWrap: always
semi: false
singleQuote: true
tabWidth: 2
trailingComma: all
pluginSearchDirs:
  - ./node_modules
plugins:
  - ./node_modules/prettier-plugin-packagejson